model:
  base_learning_rate: 4.5e-06
  target: ldm.models.autoencoder.VQModelInterface
  params:
    embed_dim: 4
    n_embed: 8192
    monitor: val/rec_loss
    ddconfig:
      double_z: false
      z_channels: 4
      resolution: 32
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.5
      tanh_out: true
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_start: 0
        disc_weight: 0.75
        disc_num_layers: 3
        codebook_weight: 1.0
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32
    wrap: true
    num_workers: 16
    train:
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: data/cifar10_train.txt
        size: 32
        flip_p: 0.5
    validation:
      target: taming.data.custom.CustomTest
      params:
        test_images_list_file: data/cifar10_validation.txt
        size: 32
        flip_p: 0.5
